import os
import tempfile
import uuid
from graphviz import Source
import matplotlib.pyplot as plt

def render_matplotlib(code, output_dir):
    """
    Executes matplotlib code to generate an image.
    The code is expected to save the figure to 'temp_graph.png'
    """
    image_path = os.path.join(output_dir, f"plot_{uuid.uuid4().hex}.png")

    # We replace 'temp_graph.png' with our actual path to intercept the save
    safe_code = code.replace("'temp_graph.png'", f"'{image_path}'")
    safe_code = safe_code.replace('"temp_graph.png"', f"'{image_path}'")

    try:
        # Execute the python code generated by LLM
        # Note: In a true production env with untrusted users, you'd sandbox this.
        # Here we trust the LLM output for demonstration purposes.
        exec(safe_code, {"plt": plt})

        # Ensure plot is closed to free memory
        plt.close('all')

        if os.path.exists(image_path):
            return image_path
        return None
    except Exception as e:
        print(f"Error rendering matplotlib: {e}")
        return None

def render_graphviz(code, output_dir):
    """
    Renders graphviz DOT language to a PNG image.
    """
    image_path = os.path.join(output_dir, f"graph_{uuid.uuid4().hex}")

    try:
        s = Source(code, filename=image_path, format="png")
        s.render()

        # Graphviz render creates the file with the format extension appended
        actual_path = f"{image_path}.png"

        if os.path.exists(actual_path):
            return actual_path
        return None
    except Exception as e:
        print(f"Error rendering graphviz: {e}")
        return None

def process_diagrams(content_elements, output_dir):
    """
    Iterates through the generated content, renders diagrams,
    and adds the local image paths back into the element dictionary.
    """
    for element in content_elements:
        if element['type'] == 'diagram_matplotlib':
            img_path = render_matplotlib(element['code'], output_dir)
            if img_path:
                element['image_path'] = img_path

        elif element['type'] == 'diagram_graphviz':
            img_path = render_graphviz(element['code'], output_dir)
            if img_path:
                element['image_path'] = img_path

        # For mermaid, we might just pass the code directly to streamlit later
        # or render via an external API. Streamlit has a st_mermaid component,
        # but for .docx we might need an image.
        # For this prototype, we will handle mermaid rendering externally or skip docx embed
        # if an image renderer isn't easily available in pure python.

    return content_elements
